baseurl: ""
url: "http://pedromarins.com"
domain: pedromarins.com
commentlinks: true

title: Pedro Marins
email: contato@pedromarins.com
description: > #
  front-end developer and events organizer with a passion for teaching and startups
twitter_username: http://twitter.com/pedromarins
github_username:  http://github.com/pedromarins
facebook_username:  http://facebook.com/pedrolmarins
linkedin_username:  http://linkedin.com/in/pedromarins

permalink: /:title/


# Build settings
markdown: kramdown





