safe:        false
baseurl:     /
url: http://blog.riojs.org/

name: Pedro Marins
title: Pedro Marins
description: front-end developer and events organizer with a passion for teaching and startups
url: http://localhost:4000
domain: pedromarins.com
commentlinks: true

source:      .
destination: ./_site
plugins:     ./_plugins

twitter_username: http://twitter.com/pedromarins
github_username:  http://github.com/pedromarins
facebook_username:  http://facebook.com/pedrolmarins
linkedin_username:  http://linkedin.com/in/pedromarins

excerpt_separator: "<!--more-->"
permalink: /:title/


markdown: kramdown

sass:
    sass_dir: assets/css